### PR TITLE
Add support for GCP MetadataServer token providers

### PR DESCRIPTION
**Pull request by boulos**
Hello! First time caller, long-time listener.

Like issue #39, I wanted to support "get a token from the metadata server" in gcsfuser [1]. This way, users don't have to export their service account keys (which is a security risk if your key file is misplaced).

I'm new-ish to Rust, so I tried to make this fairly minimal, but I'd be happy to redo whatever you folks suggest. In particular, using TokenProvider as a trait is a bit awkward, since `get_token` and `parse_token_response` are both templated (and so callers can't just hold TokenProvider or dyn TokenProvider or anything like that).

In my usage in gcsfuser, I changed my auth.rs like so to "simulate" the kind of dispatch I wanted, which is kind of sad:

```
diff --git a/src/auth.rs b/src/auth.rs
index cdef757..2754129 100644
--- a/src/auth.rs
+++ b/src/auth.rs
@@ -21,16 +21,24 @@ use tame_oauth::gcp::prelude::*;
 
 use crate::errors::HttpError;
 
+enum TokenProviderWrapper {
+    Metadata(MetadataServerProvider),
+    ServiceAccount(ServiceAccountAccess),
+}
+
 lazy_static! {
-    static ref TOKEN_PROVIDER: Option<ServiceAccountAccess> = {
+    static ref TOKEN_PROVIDER: Option<TokenProviderWrapper> = {
     // Read in the usual key file.
     let env_key = "GOOGLE_APPLICATION_CREDENTIALS";
     let cred_env = std::env::var(env_key);
     let cred_path = match cred_env {
         Ok(path) => path,
         Err(std::env::VarError::NotPresent) => {
-        info!("{} not set. Assuming public buckets", env_key);
-        return None
+        // If we're on GCP, use the Metadata server
+        debug!("Going to use the metadata server");
+        return Some(TokenProviderWrapper::Metadata(MetadataServerProvider::new(None)));
+            //info!("{} not set. Assuming public buckets", env_key);
+            //return None;
         },
         Err(error) => panic!("Invalid {}. Error {:?}", env_key, error)
     };
@@ -40,7 +48,7 @@ lazy_static! {
     let key_data = std::fs::read_to_string(cred_path).expect("failed to read credential file");
     let acct_info = ServiceAccountInfo::deserialize(key_data).expect("failed to decode credential file");
 
-    Some(ServiceAccountAccess::new(acct_info).expect("failed to create OAuth Token Provider"))
+    Some(TokenProviderWrapper::ServiceAccount(ServiceAccountAccess::new(acct_info).expect("failed to create OAuth Token Provider")))
     };
 }
 
@@ -49,8 +57,8 @@ lazy_static! {
 async fn do_http_request(
     request: http::Request<Vec<u8>>,
 ) -> Result<http::Response<Vec<u8>>, HttpError> {
-    // We only expect a POST.
-    assert_eq!(request.method(), http::Method::POST);
+    // We only expect a GET (metadata server) or POST (service account oauth token).
+    assert!(request.method() == http::Method::POST || request.method() == http::Method::GET);
 
     let https = hyper_rustls::HttpsConnector::with_native_roots();
     let client = hyper::Client::builder().build::<_, hyper::Body>(https);
@@ -79,9 +87,12 @@ async fn get_token() -> Result<Option<String>, HttpError> {
         return Ok(None);
     }
 
-    let provider = TOKEN_PROVIDER.as_ref().unwrap();
+    let wrapper = TOKEN_PROVIDER.as_ref().unwrap();
 
-    let token_or_req = provider.get_token(&scopes).unwrap();
+    let token_or_req = match wrapper {
+        TokenProviderWrapper::Metadata(x) => x.get_token(&scopes).unwrap(),
+        TokenProviderWrapper::ServiceAccount(x) => x.get_token(&scopes).unwrap(),
+    };
 
     let token = match token_or_req {
         TokenOrRequest::Request {
@@ -92,7 +103,14 @@ async fn get_token() -> Result<Option<String>, HttpError> {
             let response = do_http_request(request).await?;
 
             // Parse and unwrap the token.
-            provider.parse_token_response(scope_hash, response).unwrap()
+            match wrapper {
+                TokenProviderWrapper::Metadata(x) => {
+                    x.parse_token_response(scope_hash, response).unwrap()
+                }
+                TokenProviderWrapper::ServiceAccount(x) => {
+                    x.parse_token_response(scope_hash, response).unwrap()
+                }
+            }
         }
         TokenOrRequest::Token(token) => token,
     };
```

[1] https://github.com/GoogleCloudPlatform/gcsfuser

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
Thanks for the PR! Will take a look tomorrow.

**Comment by boulos** [comment]
Hmm. I ran cargo clippy on each commit... is there some flag I need to pass to do this locally?

**Comment by Jake-Shadle** [comment]
My guess is that you are not using Rust 1.54 which was just released today, and that particular lint became more aggressive in 1.54

**Comment by boulos** [comment]
Thanks for pointing that out, yesterday. Rebased and pushed.

**Review by Jake-Shadle — APPROVED** [review]
Thanks for the PR, we don't use metadata servers AFAIK so I'll just assume that you've tested this on your own and it works. :sweat_smile:

**Comment by boulos** [comment]
Yep! Just tested my updated code from the first comment with

`+tame-oauth = { version = "0.5", git = "https://github.com/EmbarkStudios/tame-oauth" }` 

as my dep in Cargo.toml.

What's your preference on bumping the version number / doing a release for this?

(And thanks again for the review, I know the timezone gap is a challenge!)

**Comment by Jake-Shadle** [comment]
I want to resolve #39 before doing another release but if you really need it I don't mind bumping versions.

**Comment by boulos** [comment]
I was going to comment on #39 that it’s not clear to me how to do it
“sans-io”. Does checking the file system (or even environment variables)
still count as sans-io?

In gcsfuser, I’m slowly getting to the same logic (next up would be to look
for and parse the gcloud default credentials files, before falling back to
metadata lookups when on GCE, but I’d probably only support the modern
form).

Even checking “is on a system with metadata server” requires I/O.

**Comment by Jake-Shadle** [comment]
In the context of this library I've always considered sans-io to only apply to network I/O, not disk etc, because the point of this library over other similar ones is that you can use any HTTP client you wish rather than having it forced on you.

**Pull request merged**
